Fix broken CI due to Markupsafe pip install error
Fixed by updating markupsafe dependency to 1.1. Learned that earlier versions depend on a deprecated "Feature" setuptools class that has been removed in version 46.0, therefore pip errors with:
"ImportError: cannot import name 'Feature' from 'setuptools'"

Asana card:
https://app.asana.com/0/1145671275220852/1166272671703297